SELECT	COLUMN_NAME, DATA_TYPE, 
		isnull(CHARACTER_MAXIMUM_LENGTH, -1) as CHARACTER_MAXIMUM_LENGTH, 
		isnull(CHARACTER_SET_NAME, 'NONE') as CHARACTER_SET_NAME,
		IsPK = CASE WHEN EXISTS(SELECT * 
								FROM {0}.INFORMATION_SCHEMA.TABLE_CONSTRAINTS [tc] 
									JOIN {0}.INFORMATION_SCHEMA.KEY_COLUMN_USAGE [ku] 
									ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME 
									AND ku.table_name = N'{1}' 
									AND CONSTRAINT_TYPE=N'PRIMARY KEY'
									AND ku.COLUMN_NAME = {0}.INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME)
					THEN 1 else 0
			   END

FROM {0}.INFORMATION_SCHEMA.COLUMNS WHERE (TABLE_NAME = N'{1}')