//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidCodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidCodeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.utils;
        ///
        ///import android.app.Activity;
        ///import android.content.Context;
        ///import android.content.pm.ActivityInfo;
        ///import android.content.res.Configuration;
        ///
        ////* Created by DrTJ @ April 2015 */
        ///
        ///public class ActivityUtils {
        ///    public static void SetOrientation(Activity context, Orientations tabletOrientation, Orientations phoneOrientation) {
        ///        Orientations orientation = (isTablet(context)) ? tabletOrientation : phoneOrientation;
        ///        int Orientation = orientation == O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivityUtils {
            get {
                return ResourceManager.GetString("ActivityUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package {PackageName};
        ///
        ///import android.database.Cursor;
        ///import android.os.Parcel;
        ///import android.os.Parcelable;
        ///import org.json.JSONException;
        ///import org.json.JSONObject;
        ///import java.sql.Blob;
        ///
        ////* Created by Dr TJ @ March 2015 */
        ///
        ///public class {TableName} implements Parcelable {
        ///	public static String TAG = &quot;{TableName}&quot;;
        ///
        ///    {PropertyDeclaration()}
        ///
        ///	{columnNamesAsStringList()}
        ///
        ///    public {TableName}() { }
        ///
        ///	public {TableName}({ConstructorParameters}) { 
        ///		{ConstructorAssignments()}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassDef {
            get {
                return ResourceManager.GetString("ClassDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.DataLib;
        ///
        ///import java.util.List;
        ///
        ////* Created by DrTJ @ March 2015 */
        ///
        ///public class Column {
        ///
        ///	public String Name;
        ///	public String ColumnType;
        ///	public boolean Boolean1;
        ///	public boolean Boolean2;
        ///	
        ///	public static String GetDefenitionForCreateTable(List&lt;Column&gt; columns) {
        ///		String res = &quot;&quot;;
        ///		
        ///		for (Column column : columns) {
        ///			if(res.length() &gt; 0)
        ///				res += &quot;,&quot;;
        ///			
        ///			res += &quot;`{ColumnName}` {ColumnType}&quot;.replace(&quot;{ColumnName}&quot;, column.Name)
        ///												.replace [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.utils;
        ///
        ////* Created by DrTJ @ September 2015 */ 
        ///
        ///public class CurrentUser {
        ///	public static int UserID = -1;
        ///	public static String Username = &quot;&quot;;
        ///	public static String DisplayName = &quot;&quot;;
        ///	
        ///	public static void SetUser(int id, String username, String displayName){
        ///		CurrentUser.UserID = id;
        ///		CurrentUser.Username = username;
        ///		CurrentUser.DisplayName = displayName;
        ///	}
        ///}
        ///
        ///
        ///.
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package {PackageName};
        ///
        ///import android.database.sqlite.SQLiteDatabase;
        ///import android.content.ContentValues;
        ///import android.content.Context;
        ///import android.database.Cursor;
        ///import java.util.ArrayList;
        ///import java.util.List;
        ///import ir.royapajoohesh.DataLib.TableBase;
        ///
        ////* Created by Dr TJ @ March 2015  */
        ///
        ///public class {TableName}DataSource {
        ///	public static String TAG = &quot;{TableName}DataSource&quot;;
        ///
        ///    SQLiteDatabase database;
        ///    {TableName}OpenHelper dbHelper;
        ///
        ///    public static String[] AllC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.utils;
        ///import android.os.AsyncTask;
        ///
        ///import java.net.URL;
        ///
        ////* Created by DrTJ @ April 2015 */
        ///
        ///public class FileDownloader extends AsyncTask&lt;URL, Integer, Void&gt; {
        ///	public static String TAG = &quot;FileDownloader&quot;;
        ///
        ///    String fileURL;
        ///    Byte[] data;
        ///
        ///    public FileDownloader(String url) {
        ///        this.fileURL = url;
        ///    }
        ///
        ///    public interface downloadCompleteListener{
        ///        void OnDownloadCompleted(String url, Byte[] data);
        ///        void OnDownloadFailed(String ur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileDownloader {
            get {
                return ResourceManager.GetString("FileDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	COLUMN_NAME, DATA_TYPE, 
        ///		isnull(CHARACTER_MAXIMUM_LENGTH, -1) as CHARACTER_MAXIMUM_LENGTH, 
        ///		isnull(CHARACTER_SET_NAME, &apos;NONE&apos;) as CHARACTER_SET_NAME,
        ///		IsPK = CASE WHEN EXISTS(SELECT * 
        ///								FROM {0}.INFORMATION_SCHEMA.TABLE_CONSTRAINTS [tc] 
        ///									JOIN {0}.INFORMATION_SCHEMA.KEY_COLUMN_USAGE [ku] 
        ///									ON tc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME 
        ///									AND ku.table_name = N&apos;{1}&apos; 
        ///									AND CONSTRAINT_TYPE=N&apos;PRIMARY KEY&apos;
        ///									AND ku.COLUMN_NAME = {0}.INFORMATION_SCHEMA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetColumns {
            get {
                return ResourceManager.GetString("GetColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.utils;
        ///
        ///import android.content.Context;
        ///import android.graphics.Bitmap;
        ///import android.graphics.BitmapFactory;
        ///import android.os.AsyncTask;
        ///import android.util.Log;
        ///import android.view.View;
        ///import android.widget.Button;
        ///import android.widget.ImageView;
        ///import android.widget.ProgressBar;
        ///import android.widget.TextView;
        ///import android.widget.Toast;
        ///
        ///import java.io.IOException;
        ///import java.io.InputStream;
        ///import java.net.HttpURLConnection;
        ///import java.net.URL;
        ///
        ////* C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImageDownloader {
            get {
                return ResourceManager.GetString("ImageDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.utils;
        ///
        ///public class KeyValuePair&lt;T1, T2&gt; {
        ///	public T1 Key;
        ///	public T2 Value;
        ///
        ///	public KeyValuePair(T1 key, T2 value) {
        ///		this.Key = key;
        ///		this.Value = value;
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string KeyValuePair {
            get {
                return ResourceManager.GetString("KeyValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package {PackageName};
        ///
        ///import android.content.Context;
        ///import android.database.sqlite.SQLiteDatabase;
        ///import android.database.sqlite.SQLiteOpenHelper;
        ///import ir.royapajoohesh.DataLib.TableBase;
        ///
        ////* Created by Dr TJ @ March 2015 */
        ///
        ///public class {TableName}OpenHelper extends SQLiteOpenHelper {
        ///	public static String TAG = &quot;{TableName}OpenHelper&quot;;
        ///
        ///    public TableBase {TableName}Table = null;
        ///
        ///    public static final String DatabaseName = &quot;{DatabaseName}.db&quot;;
        ///    public static final String Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenHelper {
            get {
                return ResourceManager.GetString("OpenHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.utils;
        ///
        ////* Created by DrTJ @ April 2015 */
        ///
        ///public enum Orientations{ Portrait, Landscape }
        ///.
        /// </summary>
        internal static string Orientations {
            get {
                return ResourceManager.GetString("Orientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package ir.royapajoohesh.DataLib;
        ///
        ///import java.util.ArrayList;
        ///import java.util.List;
        ///import android.database.sqlite.SQLiteDatabase;
        ///import android.database.Cursor;
        ///
        ////* Created by DrTJ @ March 2015 */
        ///
        ///
        ///public class TableBase {
        ///	public static String TAG = &quot;TableBase&quot;;
        ///
        ///	public String DatabaseName;
        ///	public String TableName;
        ///	public List&lt;Column&gt; Columns;
        ///
        ///	public TableBase(String databasename, String tablename) {
        ///		this.DatabaseName = databasename;
        ///		this.TableName = tablename;
        ///		this.Colu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableBase {
            get {
                return ResourceManager.GetString("TableBase", resourceCulture);
            }
        }
    }
}
